
name: Deploy to GitHub Pages

on: 
  push:
    branches: [ deploy-to-gh-pages ]

permissions:
  contents: read  
  pages: write      
  id-token: write   
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source  
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 22.14.0
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build      
      - name: Upload artifacts
        uses: actions/porto@v3   
        with:
           name: 'github-pages'
           path: build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'
